API - fixed internal links
AppsFlyerSDK/appsflyer-react-native-plugin pull request #589
Opened 2024-11-17 16:34 UTC by dori-af

@liaz-af
Internal links didn't work, so I changed them to small case and removed problematic characters from the ad revenue heading.

2024-11-17 21:19 UTC, liaz-af commented on Docs/RN_API.md
>      - [startSdk](#startsdk)
@dori-af why didn't these line also unindented?

2024-12-06 12:05 UTC, dori-af commented
Fixed

2024-12-15 09:59 UTC, liaz-af requested changes

2024-12-15 09:59 UTC, liaz-af commented on Docs/RN_API.md
> +  - [logAdRevenue from v6.15.1](#logadrevenue-from-v6151)
Why do we comments in the title?
Remove it please

2024-12-15 13:32 UTC, liaz-af approved these changes

2024-12-15 13:33 UTC, merged